networks:
  external:
    name: gateway
    external: true

volumes:
  pgdata:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy:2.9
    networks:
      - external
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

