networks:
  external:
    name: gateway
    external: true

services:
  caddy:
    image: caddy:2.9
    networks:
      - external
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certificates:/data/caddy/pki/authorities/local/
    restart: unless-stopped

